apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.Ingress.Name }}.{{ .Values.Ingress.Secret }}
    http:
      paths:
      - backend:
          serviceName: proxy-public 
          servicePort: 80
        path: /
  tls:
  - hosts:
    - {{ .Values.Ingress.Name }}.{{ .Values.Ingress.Secret }}
    secretName: {{ .Values.Ingress.Secret }}
