apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    component: proxy-public
  name: proxy-public
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    component: proxy
  type: ClusterIP

